### ISSUE TITLE
Glowny baner ze zdjeciami

### ISSUE THREAD

**Issue by kolenderski** [gustawdaniel/single_photons_application#7]
Odkomentowalem co trzeba, zeby bylo wiecej przewijajacych sie fotografi. dodalem tez foto o nazwei 6_rezised.jpg, zeby zobaczyc czy bedzie sie przewijalo. Przewinac sie nie chce.Zerkniesz?

**Comment by gustawdaniel** [comment]
zajmę się tym jutro.

**Comment by kolenderski** [comment]
Tak. Pogrzbalem i chyba jest zrobione ok.
