### ISSUE TITLE
Sekcja Collaborators

### ISSUE THREAD

**Issue by kolenderski** [gustawdaniel/single_photons_application#8]
Zmniejszylem mape i dodalem paru wspolpracownikow. Czy moglbys mi pomoc zrobic tak zeby te male "okienka" z informacja na temat wspolpracownika otaczaly mape?

**Comment by gustawdaniel** [comment]
zajmę się tym jutro, chociaż mam wrażenie, że to już jest dobrze.

**Comment by kolenderski** [comment]
Tak. Pogrzbalem i chyba jest zrobione ok.
